import random

names = ["OLIVER","JACK","HARRY","JACOB","CHARLIE","THOMAS","GEORGE","OSCAR","JAMES","WILLIAM","NOAH","ALFIE","JOSHUA","MUHAMMAD","HENRY","LEO","ARCHIE","ETHAN","JOSEPH","FREDDIE","SAMUEL","ALEXANDER","LOGAN","DANIEL","ISAAC","MAX","MOHAMMED","BENJAMIN","MASON","LUCAS","EDWARD","HARRISON","JAKE","DYLAN","RILEY","FINLEY","THEO","SEBASTIAN","ADAM","ZACHARY","ARTHUR","TOBY","JAYDEN","LUKE","HARLEY","LEWIS","TYLER","HARVEY","MATTHEW","DAVID","REUBEN","MICHAEL","ELIJAH","KIAN","TOMMY","MOHAMMAD","BLAKE","LUCA","THEODORE","STANLEY","JENSON","NATHAN","CHARLES","FRANKIE","JUDE","TEDDY","LOUIE","LOUIS","RYAN","HUGO","BOBBY","ELLIOTT","DEXTER","OLLIE","ALEX","LIAM","KAI","GABRIEL","CONNOR","AARON","FREDERICK","CALLUM","ELLIOT","ALBERT","LEON","RONNIE","RORY","JAMIE","AUSTIN","SETH","IBRAHIM","OWEN","CALEB","ELLIS","SONNY","ROBERT","JOEY","FELIX","FINLAY","JACKSON","","TOP GIRLS","","AMELIA","OLIVIA","ISLA","EMILY","POPPY","AVA","ISABELLA","JESSICA","LILY","SOPHIE","GRACE","SOPHIA","MIA","EVIE","RUBY","ELLA","SCARLETT","ISABELLE","CHLOE","SIENNA","FREYA","PHOEBE","CHARLOTTE","DAISY","ALICE","FLORENCE","EVA","SOFIA","MILLIE","LUCY","EVELYN","ELSIE","ROSIE","IMOGEN","LOLA","MATILDA","ELIZABETH","LAYLA","HOLLY","LILLY","MOLLY","ERIN","ELLIE","MAISIE","MAYA","ABIGAIL","ELIZA","GEORGIA","JASMINE","ESME","WILLOW","BELLA","ANNABELLE","IVY","AMBER","EMILIA","EMMA","SUMMER","HANNAH","ELEANOR","HARRIET","ROSE","AMELIE","LEXI","MEGAN","GRACIE","ZARA","LACEY","MARTHA","ANNA","VIOLET","DARCEY","MARIA","MARYAM","BROOKE","AISHA","KATIE","LEAH","THEA","DARCIE","HOLLIE","AMY","MOLLIE","HEIDI","LOTTIE","BETHANY","FRANCESCA","FAITH","HARPER","NANCY","BEATRICE","ISABEL","DARCY","LYDIA","SARAH","SARA","JULIA","VICTORIA","ZOE","ROBYN"]

random.seed(117)
lenn = len(names)
for i in range(1, 58):
    cid = 1000000 + i
    fn = names[random.randint(0, lenn-1)]
    ln = names[random.randint(0, lenn-1)]
    pn = random.randint(1111111111, 9000000000)
    an = random.randint(1111111111, 9999999999)
    username = "{}.{}_{}".format(ln,fn, random.randint(0, 200))
    password = username + "pAssWd"
    email = "{}@gmail.com".format(username)
    print("{},{},{},{},{},{},{},{}".format(cid, fn, ln, pn, an, username, password, email))