import random

streetnames = ["Chicago Ave", 
                "Main Street",
                "Church Street",
                "Main Street North",
                "Main Street South",
                "Elm Street",
                "High Street",
                "Main Street West",
                "Washington Street",
                "Main Street East",
                "Park Avenue",
                "2nd Street",
                "Walnut Street",
                "Chestnut Street",
                "Maple Avenue",
                "Maple Street",
                "Broad Street",
                "Oak Street",
                "Center Street",
                "Pine Street",
                "River Road",
                "Market Street",
                "Water Street",
                "Union Street",
                "South Street",
                "Park Street",
                "3rd Street",
                "Washington Avenue",
                "Cherry Street",
                "North Street",
                "4th Street",
                "Court Street",
                "Highland Avenue",
                "Mill Street",
                "Franklin Street",
                "Prospect Street",
                "School Street",
                "Spring Street",
                "Central Avenue",
                "1st Street",
                "State Street",
                "Front Street",
                "West Street",
                "Jefferson Street",
                "Cedar Street",
                "Jackson Street",
                "Park Place",
                "Bridge Street",
                "Locust Street",
                "Madison Avenue",
                "Meadow Lane",
                "Spruce Street",
                "Grove Street",
                "Ridge Road",
                "5th Street",
                "Pearl Street",
                "Lincoln Street",
                "Madison Street",
                "Dogwood Drive",
                "Lincoln Avenue",
                "Pennsylvania Avenue",
                "Pleasant Street",
                "4th Street West",
                "Adams Street",
                "Jefferson Avenue",
                "3rd Street West",
                "7th Street",
                "Academy Street",
                "11th Street",
                "2nd Avenue",
                "East Street",
                "Green Street",
                "Hickory Lane",
                "Route 1",
                "Summit Avenue",
                "Virginia Avenue",
                "12th Street",
                "5th Avenue",
                "6th Street",
                "9th Street",
                "Charles Street",
                "Cherry Lane",
                "Elizabeth Street",
                "Hill Street",
                "River Street",
                "10th Street",
                "Colonial Drive",
                "Monroe Street",
                "Valley Road",
                "Winding Way",
                "1st Avenue",
                "Fairway Drive",
                "Liberty Street",
                "2nd Street West",
                "3rd Avenue",
                "Broadway",
                "Church Road",
                "Delaware Avenue",
                "Prospect Avenue",
                "Route 30",
                "Sunset Drive",
                "Vine Street",
                "Woodland Drive",
                "6th Street West",
                "Brookside Drive",
                "Hillside Avenue",
                "Lake Street",
                "13th Street",
                "4th Avenue",
                "5th Street North",
                "College Street",
                "Dogwood Lane",
                "Mill Road",
                "7th Avenue",
                "8th Street",
                "Beech Street",
                "Division Street",
                "Harrison Street",
                "Heather Lane",
                "Lakeview Drive",
                "Laurel Lane",
                "New Street",
                "Oak Lane",
                "Primrose Lane",
                "Railroad Street",
                "Willow Street",
                "4th Street North",
                "5th Street West",
                "6th Avenue",
                "Berkshire Drive",
                "Buckingham Drive",
                "Circle Drive",
                "Clinton Street",
                "George Street",
                "Hillcrest Drive",
                "Hillside Drive",
                "Laurel Street",
                "Park Drive",
                "Penn Street",
                "Railroad Avenue",
                "Riverside Drive",
                "Route 32",
                "Route 6",
                "Sherwood Drive",
                "Summit Street",
                "2nd Street East",
                "6th Street North",
                "Cedar Lane",
                "Creek Road",
                "Durham Road",
                "Elm Avenue",
                "Fairview Avenue",
                "Front Street North",
                "Grant Street",
                "Hamilton Street",
                "Highland Drive",
                "Holly Drive",
                "King Street",
                "Lafayette Avenue",
                "Linden Street",
                "Mulberry Street",
                "Poplar Street",
                "Ridge Avenue",
                "7th Street East",
                "Belmont Avenue",
                "Cambridge Court",
                "Cambridge Drive",
                "Clark Street",
                "College Avenue",
                "Essex Court",
                "Franklin Avenue",
                "Hilltop Road",
                "James Street",
                "Magnolia Drive",
                "Myrtle Avenue",
                "Route 10",
                "Route 29",
                "Shady Lane",
                "Surrey Lane",
                "Walnut Avenue",
                "Warren Street",
                "Williams Street",
                "Wood Street",
                "Woodland Avenue"]

states = ["NJ", "NC", "TX", "OR", "CO", "IA", "NY", "WA"]
cities = ["Alexander City","Andalusia","Anniston","Athens","Atmore","Auburn","Bessemer","Birmingham","Chickasaw","Clanton","Cullman","Decatur","Demopolis","Dothan","Enterprise","Eufaula","Florence","Fort Payne","Gadsden","Greenville","Guntersville","Huntsville","Jasper","Marion","Mobile","Montgomery","Opelika","Ozark","Phenix City","Prichard","Scottsboro","Selma","Sheffield","Sylacauga","Talladega","Troy","Tuscaloosa","Tuscumbia","Tuskegee","Alaska","Anchorage","Cordova","Fairbanks","Haines","Homer","Juneau","Ketchikan","Kodiak","Kotzebue","Nome","Palmer","Seward","Sitka","Skagway","Valdez","Arizona","Ajo","Avondale","Bisbee","Casa Grande","Chandler","Clifton","Douglas","Flagstaff","Florence","Gila Bend","Glendale","Globe","Kingman","Lake Havasu City","Mesa","Nogales","Oraibi","Phoenix","Prescott","Scottsdale","Sierra Vista","Tempe","Tombstone","Tucson","Walpi","Window Rock","Winslow","Yuma"]
num_street = len(streetnames)
num_states = len(states)
num_cities = len(cities)
random.seed(117)
for i in range(9, 80):
    addrid = 1000000 + i
    streetNumber = random.randint(1000, 20000)
    streetname = streetnames[random.randint(0, num_street-1)]
    city = cities[random.randint(0, num_cities-1)]
    state = states[random.randint(0, num_states-1)]
    zipcode = random.randint(10001, 99999)
    print("{},{},{},,{},{},{}".format(addrid, streetNumber, streetname, city, state, zipcode))
